### ISSUE TITLE
v1.4.0 testing on 90k sample dataset: rule sample_concordance_king exceeds time limit

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#282]
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 112
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Tue Apr 30 16:21:21 2024]
rule sample_concordance_king:
    input: sample_level/call_rate_2/samples.bed, sample_level/call_rate_2/samples.bim, sample_level/call_rate_2/samples.fam
    output: sample_level/concordance/king.kin, sample_level/concordance/king.kin0, sample_level/concordance/kingX.kin, sample_level/concordance/kingX.kin0, sample_level/concordance/kingallsegs.txt
    log: sample_level/concordance/king.log
    jobid: 0
    threads: 8
    resources: mem_mb=8192, disk_mb=31194, tmpdir=/tmp, time_hr=2

king -b sample_level/call_rate_2/samples.bed --related --degree 3 --prefix sample_level/concordance/king --cpu 8 > sample_level/concordance/king.log 2>&1 && touch sample_level/concordance/king.kin && touch sample_level/concordance/king.kin0 && touch sample_level/concordance/kingX.kin && touch sample_level/concordance/kingX.kin0 && touch sample_level/concordance/kingallsegs.txt 
Activating conda environment: /mnt/nfs/gigantor/ifs/DCEG/CGF/GWAS/Scans/GSA_Lab_QC/SR0554-001_001thru028_Combined_09262023_updated/builds/QC_v3_04302024/.snakemake/conda/0a9016efb3632d162e423f8031819bee
slurmstepd: error: *** JOB 1278976 ON node141 CANCELLED AT 2024-04-30T18:21:38 DUE TO TIME LIMIT ***

**Comment by jaamarks** [comment]
Hi @1teaspoon, did the `sample_concordance_king` rule not attempt the job again? 

The Snakemake code is set to dynamically allocate resources, as you can see below in the code snippet. In the error message you pasted above, it indicates that the `mem_mb=8192` and `time_hr=2`. This aligns with what would be a first attempt. I would expect the job to be resubmitted with `mem_mb=16384` and `time_hr=4`.

<br>

**rule sample_concordance_king**

```
   ...
    resources:
        mem_mb=lambda wildcards, attempt: 1024 * 8 * attempt,
        time_hr=lambda wildcards, attempt: 2 * attempt,
```


## Example log
<details>
<summary>Here is what I would expect the log to look like on this rule:</summary>

rule sample_concordance_king:
    input: sample_level/call_rate_2/samples.bed, sample_level/call_rate_2/samples.bim, sample_level/call_rate_2/samples.fam
    output: sample_level/concordance/king.kin, sample_level/concordance/king.kin0, sample_level/concordance/kingX.kin, sample_level/concordance/kingX.kin0, sample_level/concordance/kingallsegs.txt
    log: sample_level/concordance/king.log
    jobid: 23
    threads: 8                                                                                                              **resources: tmpdir=/tmp, mem_mb=8192, time_hr=2**

<br>
 ...
<br>

Error in rule sample_concordance_king:
    jobid: 23                                                                                                               output: sample_level/concordance/king.kin, sample_level/concordance/king.kin0, sample_level/concordance/kingX.kin, sample_level/concordance/kingX.kin0, sample_level/concordance/kingallsegs.txt                                                log: sample_level/concordance/king.log (check log file(s) for error message)                                            conda-env: /mnt/nfs/gigantor/ifs/DCEG/Home/marksja/dev-tests/012/.snakemake/conda/8f019c36f3ea263f3fa93154c692decf
    shell:                                                                                                                      king -b sample_level/call_rate_2/samples.bed --related --degree 3 --prefix sample_level/concordance/king --cpu 8 > sample_level/concordance/king.log 2>&1 && touch sample_level/concordance/king.kin && touch sample_level/concordance/king.kin0 && touch sample_level/concordance/kingX.kin && touch sample_level/concordance/kingX.kin0 && touch sample_level/concordance/kingallsegs.txt                                                                                                     (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)                    cluster_jobid: 1149622                                                                                              
Error executing rule sample_concordance_king on cluster (jobid: 23, external: 1149622, jobscript: /mnt/nfs/gigantor/ifs/DCEG/Home/marksja/dev-tests/012/.snakemake/tmp.b22jdlsh/snakejob.sample_concordance_king.23.sh). For error details see the cluster log and the log files of the involved rule(s).                                                               Removing output files of failed job sample_concordance_king since they might be corrupted:
sample_level/concordance/kingallsegs.txt
Trying to restart job 23.

Select jobs to execute...

[Tue Mar 19 16:46:55 2024]
rule sample_concordance_king:
    input: sample_level/call_rate_2/samples.bed, sample_level/call_rate_2/samples.bim, sample_level/call_rate_2/samples.fam
    output: sample_level/concordance/king.kin, sample_level/concordance/king.kin0, sample_level/concordance/kingX.kin, sample_level/concordance/kingX.kin0, sample_level/concordance/kingallsegs.txt
    log: sample_level/concordance/king.log
    jobid: 23
    threads: 8
    **resources: tmpdir=/tmp, mem_mb=16384, time_hr=4**

<br>

...

<br>


Error executing rule sample_concordance_king on cluster (jobid: 23, external: 1151106, jobscript: /mnt/nfs/gigantor/ifs/DCEG/Home/marksja/dev-tests/012/.snakemake/tmp.b22jdlsh/snakejob.sample_concordance_king.23.sh). For error details see the cluster log and the log files of the involved rule(s).
Removing output files of failed job sample_concordance_king since they might be corrupted:
sample_level/concordance/kingallsegs.txt
Trying to restart job 23.
Select jobs to execute...                                                                                                                                                                                                                       [Tue Mar 19 20:47:25 2024]
rule sample_concordance_king:
    input: sample_level/call_rate_2/samples.bed, sample_level/call_rate_2/samples.bim, sample_level/call_rate_2/samples.fam                                                                                                                         output: sample_level/concordance/king.kin, sample_level/concordance/king.kin0, sample_level/concordance/kingX.kin, sample_level/concordance/kingX.kin0, sample_level/concordance/kingallsegs.txt                                                log: sample_level/concordance/king.log                                                                                  jobid: 23
    threads: 8                                                                                                              **resources: tmpdir=/tmp, mem_mb=24576, time_hr=6**


<br>

...

<br>





Error executing rule sample_concordance_king on cluster (jobid: 23, external: 1151115, jobscript: /mnt/nfs/gigantor/ifs/DCEG/Home/marksja/dev-tests/012/.snakemake/tmp.b22jdlsh/snakejob.sample_concordance_king.23.sh). For error details see the cluster log and the log files of the involved rule(s).
Removing output files of failed job sample_concordance_king since they might be corrupted:
sample_level/concordance/kingallsegs.txt                                                                                Trying to restart job 23.                                                                                               Select jobs to execute...                                                                                                                                                                                                                       [Wed Mar 20 02:48:01 2024]                                                                                              rule sample_concordance_king:
    input: sample_level/call_rate_2/samples.bed, sample_level/call_rate_2/samples.bim, sample_level/call_rate_2/samples.fam
    output: sample_level/concordance/king.kin, sample_level/concordance/king.kin0, sample_level/concordance/kingX.kin, sample_level/concordance/kingX.kin0, sample_level/concordance/kingallsegs.txt
    log: sample_level/concordance/king.log                                                                                  jobid: 23
    **threads: 8                                                                                                              resources: tmpdir=/tmp, mem_mb=32768, time_hr=8**


</details>

Notice, it failed three times before it finally allocated 8hrs and was successful.

**Comment by jaamarks** [comment]
Note, that we didn't modify this rule in this latest version. It was last modified in 2021 by jfear.
```
efbccc1b (Justin Fear 2021-05-18 10:57:01 -0400 367)     resources:
efbccc1b (Justin Fear 2021-05-18 10:57:01 -0400 368)         mem_mb=lambda wildcards, attempt: 1024 * 8 * attempt,
efbccc1b (Justin Fear 2021-05-18 10:57:01 -0400 369)         time_hr=lambda wildcards, attempt: 2 * attempt,
```

**Comment by 1teaspoon** [comment]
Oh I see! Sorry I didn't realize it is still trying to run after failing 3 times.  It is currently running on the cluster :)
 JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           1287042   bigmemq sample_c  wangj41  R    7:34:41      1 node137

I will wait to see if this job gets finished successfully and will close this ticket.

**Comment by jaamarks** [comment]
We can edit the `time_hr` variable if you want so that it allocates more time more quickly.
Just let me know what would work best for you.

**Comment by jaamarks** [comment]
During this morning's meeting, it was decided to increase the rate at which time is allocated. Previously the N=90K sample has taken 8 hours to run, so we will increase the rate of time allocated to be 8, 16, 24... instead of the previous 2, 4, 6, 8...
This will make it likely to finish on the first run, thus saving compute resources and time.

We'll create a PR to close this issue.

**Comment by jaamarks** [comment]
We discussed this issue earlier today and had a question: What was the initial reason for not allocating a longer time when the pipeline was first created? What are the drawbacks of simply setting a very large wall-time (e.g., 48 hours) instead of dynamically allocating time? @1teaspoon

**Comment by jaamarks** [comment]
@1teaspoon, we created a branch https://github.com/NCI-CGR/GwasQcPipeline/tree/issue-282-improve-time-allocation and implemented an update to the time allocation, which we are currently testing. This new allocation is {10, 48, 96}. This will be applied to the sample_concordance_king rule, as well as the other concordance rules.
