### ISSUE TITLE
Discordant expected dup removal - only apply to replicates pass call rate & contamination

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#324]
In the example below, since SB745670_PB84781_F05 is below call rate filter, sample SB745670_PB84781_G01 should be kept for subject level analysis. Unless they are both pass call rate & contamination filter, both replicates should be removed.
![image](https://github.com/user-attachments/assets/7c69035d-9dec-43d2-9116-8d4b43451502)

**Comment by jaamarks** [comment]
## update
We are still experiencing an issue with the retention of expected replicates when one of the samples fails the call rate filters. Specifically, if we have two samples that are expected replicates and one does not pass the call rate filter, the other sample that does pass should still be retained and proceed to subject-level qc.

This did not happen in the case below though. We would expect to retain `SB745670_PB84781_G01` since its counterpart `SB745670_PB84781_F05` had a low call rate.

<span data-teams="true"><span class="ui-provider a b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak" dir="ltr">
Sample_ID | Group_By_Subject_ID | Project | Case/Control_Status | Internal Control | Number Samples Per Subject | Replicate IDs | Sample Excluded from QC | Sample Used in Subject Analysis | Subject Removed | Sample Pass QC | Low Call Rate
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SB745670_PB84781_G01 | I-0000618499 | GP0385-CI21 | Control | FALSE | 2 | SB745670_PB84781_F05\|SB745670_PB84781_G01 | FALSE | FALSE | TRUE | FALSE | FALSE
SB745670_PB84781_F05 | I-0000618499 | GP0385-CI21 | Control | FALSE | 2 | SB745670_PB84781_F05\|SB745670_PB84781_G01 | FALSE | FALSE | TRUE | FALSE | TRUE

</span></span>
